### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by justinchuby** [ScottyLabs/course-api#27]
The api gives traceback when Authenticating
The semester is "S"
```
Authenticating...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/cmu-course-api", line 48, in <module>
    data = cmu_course_api.get_course_data(semester, username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cmu_course_api/aggregate.py", line 57, in get_course_data
    fces = parse_fces(username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cmu_course_api/parse_fces.py", line 173, in parse_fces
    sessionid = authenticate(username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cmu_course_api/parse_fces.py", line 70, in authenticate
    s = cmu_auth.authenticate(LOGIN_URL, username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cmu_auth/auth.py", line 58, in authenticate
    s.post(parser.url, data=parser.to_post).content
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 450, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 381, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/models.py", line 361, in prepare_url
    "Perhaps you meant http://{0}?".format(url))
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
```

**Comment by justingallagher** [comment]
Thanks, this reproduces for me. Most likely the FCE website changed its format again. I will investigate this weekend.

**Comment by justingallagher** [comment]
This seems to be a problem with the cmu_auth library we're using to authenicate - see [here](https://github.com/willcrichton/cmu_auth/issues/3) for tracking.

**Comment by justingallagher** [comment]
The feature has been removed - see #11 for efforts to re-add it.
