### ISSUE TITLE
New upgrade is broken

### ISSUE THREAD

**Issue by nitsanshai** [ScottyLabs/course-api#46]
I ran the command
`cmu-course-api F ./f16.json`

The script ran for a long time and then spit out the following error:
I got the following error:
Traceback (most recent call last):
  File "/usr/local/bin/cmu-course-api", line 48, in <module>
    data = cmu_course_api.get_course_data(semester, username, password)
  File "/usr/local/lib/python3.5/site-packages/cmu_course_api/aggregate.py", line 79, in get_course_data
    return aggregate(schedules, fces)
  File "/usr/local/lib/python3.5/site-packages/cmu_course_api/aggregate.py", line 44, in aggregate
    desc = get_course_desc(course['num'], semester, year)
  File "/usr/local/lib/python3.5/site-packages/cmu_course_api/parse_descs.py", line 153, in get_course_desc
    desc = soup.find(id='course-detail-description').p.string
AttributeError: 'NoneType' object has no attribute 'find'

These are the last three printouts before the error:
Getting description for 03711...
Getting description for 03712...
Getting description for 03726...

**Comment by nitsanshai** [comment]
Looks like I was having internet issues, I can't replicate this.
