### ISSUE TITLE
Stuck while acquiring data

### ISSUE THREAD

**Issue by justinchuby** [ScottyLabs/course-api#53]
While running `cmu_course_api.get_course_data()`, the program hangs.
```
Getting description for 47998...
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "generate_ES_command.py", line 45, in generate_from_course_api
    scotty_data = cmu_course_api.get_course_data(semester)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cmu_course_api/aggregate.py", line 104, in get_course_data
    return aggregate(schedules)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cmu_course_api/aggregate.py", line 90, in aggregate
    queue.join()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/queue.py", line 83, in join
    self.all_tasks_done.wait()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
```

**Comment by justinchuby** [comment]
It hangs when an error is thrown in a thread.
